### ISSUE TITLE
conjurDatabaseUrl should not ask for base64 encoded strings

### ISSUE THREAD

**Issue by deci-ftw** [cyberark/conjur-google-cloud-marketplace#5]
In the deployers `schema.yaml`, the `conjurDatabaseUrl` property currently takes in a base64 encoded string. This should be updated to use new features in the [v0.6.2 Beta Release](https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/releases/tag/v0.6.2) of the marketplace-k8s-app-tools repo, which allows entry of a non encoded string, and will encode it for you.

**Comment by dustinmm80** [comment]
Hi Frank, this is now fixed, in https://github.com/cyberark/conjur-google-cloud-marketplace/commit/7b1d6c200cfa0a7e10793fcb90c6e05c9e85786c.

Closing this, thanks!
